---

- name: configure hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: update hosts file
  replace:
    path: /etc/hosts
    regexp: 'raspberrypi'
    replace: '{{ inventory_hostname }}'

- name: disable power save from wlan0 interface
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: '0755'

# FIX warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
- name: enable en_us.utf8 in locale.gen
  replace:
    path: /etc/locale.gen
    regexp: '^# en_US.UTF-8 UTF-8'
    replace: 'en_US.UTF-8 UTF-8'
  notify: exec locale-gen

- name: configure timezone to Europe/Helsinki
  timezone:
    name: Europe/Helsinki
  notify: restart rsyslog

- name: configure syslog timestamp
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart rsyslog

- name: flush handlers
  meta: flush_handlers

- name: configure ntp
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart systemd-timesyncd

- name: harden ssh config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: restart sshd

- name: disable core dump | limits.conf
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: '0644'

- name: disable core dump | sysctl
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: '0644'

- name: disable unnecessary protocols
  copy:
    src: blacklist-protocols.conf
    dest: /etc/modprobe.d/blacklist-protocols.conf
    owner: root
    group: root
    mode: '0644'

- name: harden password hashing rounds
  template:
    src: login.defs.j2
    dest: /etc/login.defs
    owner: root
    group: root
    mode: '0644'

- name: add legal banners
  template:
    src: "{{ item }}.j2"
    dest: /etc/{{ item }}
    owner: root
    group: root
    mode: '0644'
  with_items:
    - issue
    - issue.net

- name: disable unnecessary services
  service:
    name: "{{ item }}"
    enabled: no
  with_items:
#        - alsa-state    # audio related stuff
    - avahi-daemon  # zeroconf service discovery
    - triggerhappy  # physical keyboard stuff
#        - systemd-ask-password-console
#        - systemd-ask-password-wall

- name: install unattended-upgrades
  apt:
    name: unattended-upgrades

- name: configure unattended-upgrades
  copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'

- name: install ufw
  apt:
    name: ufw
    autoremove: yes

- name: configure ufw to allow ssh
  ufw:
    rule: allow
    name: OpenSSH
  ignore_errors: "{{ ansible_check_mode }}"

- name: enable ufw
  ufw:
    state: enabled
  ignore_errors: "{{ ansible_check_mode }}"

- name: install utils
  apt:
    name: "{{ item }}"
  with_items:
    - vim
    - apt-show-versions

- name: configure swappiness
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present

- name: update all installed packages
  apt:
    name: "*"
    state: latest
    update_cache: yes
  notify: restart computer

- name: upgrade the operating system
  apt:
    upgrade: dist
  notify: restart computer
