---

- name: restart sshd
  systemd:
    name: sshd
    state: restarted
  become: yes

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
  become: yes

- name: exec locale-gen
  command:
    cmd: /usr/sbin/locale-gen

- name: restart systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted

- name: restart computer
  reboot:
  become: yes
